- name: Install nagios plugins for monitoring via itcockpit
  apt:
    name: ["nagios-plugins","nagios-nrpe-server"]
    state: present
  become: yes

- name: append itcockpit server to the list of allowed hosts
  lineinfile:
    path: /etc/nagios/nrpe.cfg
    backrefs: yes
    regexp: "^(.*allowed_hosts.*)$"
    line: 'allowed_hosts=127.0.0.1,::1,{{ itcockpit_server }}'
  become: yes
  register: nagios_cfg

- name: reload nagios service
  systemd:
    state: reloaded
    name: nagios-nrpe-server
  become: yes
  when: nagios_cfg.changed