# Run copy file and run docker compose
#
- name: install python3
  apt:
    name: python3
    state: present
  become: yes

- name: install setuptools
  apt:
    name: python3-setuptools
    state: present
  become: yes

- name: install pip
  apt:
    name: python3-pip
    state: present
  become: yes

- name: install docker-compose
  pip:
    name: docker-compose
    executable: pip3
  become: yes

- name: Copy docker-compose.yml
  copy:
    src: "{{ compose_file_path }}"
    dest: "{{ dest_compose_file_path }}"
  become: yes
  register: compose_config

- name: run docker compose
  docker_compose:
    state: present
    build: True
    project_src: "{{ dest_compose_file_path }}"
    project_name: "flowable_openforecast"
    files: "docker-compose.yml"
  become: yes
  when: compose_config.changed

#
# Copy and install nginx configuration
#
- name: create folder for the certs
  file:
    path: /root/cert
    state: directory
  become: yes

- name: copy certifcate file
  copy:
    src: "{{ item }}"
    dest: /root/cert/
  with_items: ["roles/flowable/files/cert.pem","roles/flowable/files/key.pem"]
  register: nginx_cert
  become: yes

- name: add nginx configuration
  copy:
    src: roles/flowable/files/flow_nginx.conf
    dest: /etc/nginx/sites-enabled
  become: yes
  register: nginx_config

- name: remove nginx default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: reload nginx
  command:
    cmd: nginx -s reload
  become: yes
  when: nginx_config.changed or nginx_cert.changed
